server:
  port: 8082

spring:
  application:
    name: sample-service
  datasource:
    url: jdbc:mysql://localhost:3306/labresults
    username: labresults
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

springdoc:
  api-docs:
    path: /sample/v3/api-docs
  swagger-ui:
    path: /sample/swagger-ui.html
