apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: labresults
spec:
  type: ClusterIP
  selector:
    app: sample-service
  ports:
    - protocol: TCP
      targetPort: 8082
      port: 8082