apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: labresults
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - protocol: TCP
      targetPort: 8083
      port: 8083