apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: labresults
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: jchojdak/labresults:eureka-server
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8761
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888