apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: labresults
spec:
  type: LoadBalancer
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      targetPort: 8761
      port: 8761