apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: labresults
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.3
          args: ["start-dev", "--import-realm"]
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import/realm-export.json
              subPath: realm-export.json
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: keycloak-config
      volumes:
        - name: realm-import
          hostPath:
            path: /keycloak/realm-export.json
            type: File