apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: labresults
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      targetPort: 8081
      port: 8081