apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: labresults
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: jchojdak/labresults:config-server
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: native
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: CONFIG_EUREKA_URL
              value: http://eureka-server:8761/eureka/
            - name: CONFIG_KEYCLOAK_URL
              value: http://keycloak:8081/realms/labresults/protocol/openid-connect/certs