apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: labresults
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
    - protocol: TCP
      targetPort: 8888
      port: 8888
