server:
  port: 8085

spring:
  datasource:
    url: ${CONFIG_POSTGRES_URL:jdbc:postgresql://localhost:5432/labresults}
    username: labresults
    password: labresults
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
  mail:
    host: smtp.gmail.com
    port: 587
    username: labresults@gmail.com
    password: labresultspassword
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  mail-from: labresults@gmail.com

eureka:
  client:
    service-url:
      defaultZone: ${CONFIG_EUREKA_URL:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /notification/v3/api-docs
  swagger-ui:
    path: /notification/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always