server:
  port: 8085

spring:
  datasource:
    url: ${CONFIG_POSTGRES_URL:jdbc:postgresql://localhost:5432/labresults}
    username: ${CONFIG_POSTGRES_USERNAME:labresults}
    password: ${CONFIG_POSTGRES_PASSWORD:labresults}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    username: ${CONFIG_RABBITMQ_USERNAME:user}
    password: ${CONFIG_RABBITMQ_PASSWORD:password}
    host: ${CONFIG_RABBITMQ_HOST:localhost}
    port: ${CONFIG_RABBITMQ_PORT:5672}
  mail:
    host: ${CONFIG_SMTP_HOST:smtp.gmail.com}
    port: ${CONFIG_SMTP_PORT:587}
    username: ${CONFIG_SMTP_USERNAME:labresults@gmail.com}
    password: ${CONFIG_SMTP_PASSWORD:labresultspassword}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  mail-from: ${CONFIG_MAIL_FROM:labresults@gmail.com}

eureka:
  client:
    service-url:
      defaultZone: ${CONFIG_EUREKA_URL:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /notification/v3/api-docs
  swagger-ui:
    path: /notification/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always