spring:
  datasource:
    url: ${CONFIG_POSTGRES_URL:jdbc:postgresql://postgres:5432/labresults}
  rabbitmq:
    host: rabbitmq
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: ${CONFIG_EUREKA_URL:http://eureka-server:8761/eureka/}