server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/labresults
    username: labresults
    password: labresults
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

springdoc:
  api-docs:
    path: /order/v3/api-docs
  swagger-ui:
    path: /order/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always