apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-service
  namespace: labresults
  labels:
    app: result-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-service
  template:
    metadata:
      labels:
        app: result-service
    spec:
      containers:
        - name: result-service
          image: jchojdak/labresults:result-service
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: CONFIG_POSTGRES_URL
              value: jdbc:postgresql://postgres:5432/labresults
            - name: CONFIG_EUREKA_URL
              value: http://eureka-server:8761/eureka/