apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: labresults
spec:
  type: ClusterIP
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      targetPort: 8084
      port: 8084